### ISSUE TITLE
"February" is mislabeled as "March"

### ISSUE THREAD

**Issue by ankur7york** [anubra266/choc-datetimepicker#9]
February displays as 'March':
![image](https://user-images.githubusercontent.com/43708576/160724709-1f3dc892-88de-4f9e-8d73-e2f8f0a7c518.png)
(from the[ CodeSandbox demo](https://codesandbox.io/s/github/anubra266/choc-datetimepicker/tree/main/demo))

**Comment by anubra266** [comment]
Hi @ankur7york could you shed more light on this, I could not find any issue.

**Comment by ankur7york** [comment]
Hi!  While changing the months/years, February always displayed as "March" for me - but you're right it's working fine now. Maybe because the current date is now in April?
